CREATE TABLE users (
	done  BIT NOT NULL DEFAULT 0,
	id INT NOT NULL PRIMARY KEY IDENTITY,
	name VARCHAR (100) NOT NULL,
	email VARCHAR (150) NOT NULL UNIQUE,
	phone VARCHAR(20) NULL,
	task VARCHAR(500) NOT NULL,
	admin_perms VARCHAR(3) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loginUsers (
	id INT NOT NULL PRIMARY KEY IDENTITY,
	name VARCHAR (100) NOT NULL,
	email VARCHAR (150) NOT NULL UNIQUE,
	password VARCHAR(500) NOT NULL,
	phone VARCHAR(20) NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
